### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by M7025925** [Sjj1024/douyin-live#11]
配置文件里有下面三个参数，分别在哪里获取？不使用这三个参数还能实时查看弹幕动态吗？安装依赖后，我只修改了LIVE_ROOM_URL的值，其它都没动，运行效果如下面的图，最后一个问题，你的CSDN博客里有好多文章，但我只对抖音直播间爬虫感兴趣，有没有相关的详细教程，谢谢
![image](https://github.com/Sjj1024/douyin-live/assets/103110487/9c160ebd-826d-48a1-889f-7a57120ddb18)
![image](https://github.com/Sjj1024/douyin-live/assets/103110487/44e40de0-c25d-4b3b-b7f7-56e6d375eca4)

**Comment by Sjj1024** [comment]
普通用户你只需要修改LIVE_ROOM_URL就可以监控直播数据了，其他的不用管
