### ISSUE TITLE
获取不到弹幕啊

### ISSUE THREAD

**Issue by jxyk2007** [Sjj1024/douyin-live#12]
python main.py
获取线上数据失败：URL has an invalid label.
unopened http senders
获取到的直播数据是:点赞：0, 评论: 0, 礼物价值: 0
主播账号信息: {'id_str': '62426139256', 'sec_uid': 'MS4wLjABAAAArKyDt0IEEnThKnSgcnGu12-DgUbBt4J0J0kzbFkZE0Y', 'nickname': '毛爸美食记', 'avatar_thumb': {'url_list': ['https://p3.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_97a201158859a73fba4cb064308ea9fa.jpeg?from=3067671334', 'https://p11.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_97a201158859a73fba4cb064308ea9fa.jpeg?from=3067671334', 'https://p26.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_97a201158859a73fba4cb064308ea9fa.jpeg?from=3067671334']}, 'follow_info': {'follow_status': 0, 'follow_status_str': '0'}}
直播流m3u8链接地址是: https://pull-hls-l26.douyincdn.com/third/stream-402578641154212326_or4.m3u8?expire=65991550&sign=9114b84990e8386c925fc09faeb7ade2
直播流FLV地址是: https://pull-flv-l26.douyincdn.com/third/stream-402578641154212326_sd.flv?expire=65991550&sign=ec133cd5594f47073f0fb848493b71fd
间隔10秒更新一下排行
未开启直播礼物排名

**Comment by Sjj1024** [comment]
你要更改config.py里面的直播地址啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by M7025925** [comment]
为什么我的运行效果是这样的，这正常吗？
![image](https://github.com/Sjj1024/douyin-live/assets/103110487/4b559b8c-e519-4531-8dea-df028530120e)

**Comment by Sjj1024** [comment]
你换个热门的直播间，就能抓到数据了啊
