### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZhonghuiCao** [Sjj1024/douyin-live#2]
缺少三个依赖，分别是LIVE_GIFT_LIST、GAME_UUID、LIVE_SEND_INTERVAL
LIVE_GIFT_LIST=[""]
GAME_UUID=''
LIVE_SEND_INTERVAL=''
手动配置后只能获取礼物排名，无法监听其他信息

**Comment by Sjj1024** [comment]
看使用说明，OK
