### ISSUE TITLE
websocket 连接失败

### ISSUE THREAD

**Issue by MarcoBeer** [Sjj1024/douyin-live#20]
2024-02-11 21:52:33,433 - ERROR - [onError] [webSocket Error事件] [房间Id：xxx]
2024-02-11 21:52:33,434 - ERROR - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000) - goodbye

大佬问下，我连接不到直播间，请问该怎么办啊？

**Comment by Sjj1024** [comment]
> 2024-02-11 21:52:33,433 - ERROR - [onError] [webSocket Error事件] [房间Id：xxx] 2024-02-11 21:52:33,434 - ERROR - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000) - goodbye
> 
> 大佬问下，我连接不到直播间，请问该怎么办啊？

请把直播房间的链接给我，我这边没有遇到过这种情况

**Comment by MarcoBeer** [comment]
https://live.douyin.com/601216372880  抖音网页版，随便一个直播间，都报这个错误

**Comment by MarcoBeer** [comment]
> 2024-02-11 21:52:33,433 - ERROR - [onError] [webSocket Error事件] [房间Id：xxx] 2024-02-11 21:52:33,434 - ERROR - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000) - goodbye
> 
> 大佬问下，我连接不到直播间，请问该怎么办啊？



> > 2024-02-11 21:52:33,433 - ERROR - [onError] [webSocket Error事件] [房间Id：xxx] 2024-02-11 21:52:33,434 - ERROR - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000) - goodbye
> > 大佬问下，我连接不到直播间，请问该怎么办啊？
> 
> 请把直播房间的链接给我，我这边没有遇到过这种情况

https://live.douyin.com/601216372880 抖音网页版，随便一个直播间，都报这个错误

**Comment by Sjj1024** [comment]
> https://live.douyin.com/601216372880  抖音网页版，随便一个直播间，都报这个错误

你的电脑环境说明一下，什么电脑什么系统，python版本多少，截图看一下

**Comment by MarcoBeer** [comment]
> > https://live.douyin.com/601216372880  抖音网页版，随便一个直播间，都报这个错误
> 
> 你的电脑环境说明一下，什么电脑什么系统，python版本多少，截图看一下
Python 3.12.2
MacOS sonoma 14.1.1

**Comment by Sjj1024** [comment]
> > > https://live.douyin.com/601216372880  抖音网页版，随便一个直播间，都报这个错误
> > 
> > 
> > 你的电脑环境说明一下，什么电脑什么系统，python版本多少，截图看一下
> > Python 3.12.2
> > MacOS sonoma 14.1.1

可能需要远程看一下，暂时没有这种设备电脑，没法帮你解决
