### ISSUE TITLE
发现在捕捉用户送给主播小心心时，会重复计算

### ISSUE THREAD

**Issue by hfzh06** [Sjj1024/douyin-live#30]
<img width="229" alt="Snipaste_2024-04-26_13-43-40" src="https://github.com/Sjj1024/douyin-live/assets/62101872/d4733835-04d2-4dd3-a900-c0e4ed34aaaf">
<img width="1031" alt="Snipaste_2024-04-26_13-44-39" src="https://github.com/Sjj1024/douyin-live/assets/62101872/d1a81cd9-35e7-456f-9d4c-d892ffb85e64">
在用户送一个小心心之后程序会在三四秒后重复计算。特别是用户连续点击，此时程序会当作等差数列求和，计算出来的数据特别大。还有人气票也会重复计算。其他礼物还在观察中

**Comment by Sjj1024** [comment]
看代码里面通过traceId对礼物进行重复性教研

**Comment by liulang100** [comment]
> 看代码里面通过traceId对礼物进行重复性教研

这个traceID 现在抓出来是none
