### ISSUE TITLE
ModuleNotFoundError: No module named 'proto.dy_pb2'

### ISSUE THREAD

**Issue by reallovelei** [Sjj1024/douyin-live#40]
根据协议文件生成的py里 没有class
所以总是报这个错
  File "D:\develop\git\douyin-live\src\dy_live.py", line 18, in <module>
    from protos.dy_pb2 import ChatMessage
ModuleNotFoundError: No module named 'protos.dy_pb2'

**Comment by zlpu** [comment]
在dy_p2.py 目录中添加一个__init__.py文件(空文件)

**Comment by reallovelei** [comment]
dy_p2.py 我用自己protoc 生成的还是不行，
然后还原成git上的，居然可以运行了。 
大佬，这是什么原理？能赐教一下吗？
我刚开始写python。之前是写go  php的。

**Comment by Sjj1024** [comment]
先学python和proto
